### ISSUE TITLE
优先级

### ISSUE THREAD

**Issue by crystalwm** [crystalwm/cssDemo#1]
http://bbs.csdn.net/topics/390586588

在css中有一个很重要的概念，就是优先级，不懂优先级会产生怎样的后果了？

**Comment by crystalwm** [comment]
html结构
```html
<form class="form-inline" role="form">
  <div class="form-group">
    <label class="sr-only" for="exampleInputEmail2">邮箱</label>
    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="请输入你的邮箱地址">
  </div>
  <div class="form-group">
    <label class="sr-only" for="exampleInputPassword2">密码</label>
    <input type="password" class="form-control" id="exampleInputPassword2" placeholder="请输入你的邮箱密码">
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> 记住密码
    </label>
  </div>
  <button type="submit" class="btn btn-default">进入邮箱</button>
</form>
```


```css
form-inline .form-control {
display: inline-block;
width: auto;
vertical-align: middle;}

.form-control {
display: block;
width: 100%;
height: 34px;
padding: 6px 12px;}
```



![Uploading youxianji.jpg…]()
