### ISSUE TITLE
white-space属性

### ISSUE THREAD

**Issue by crystalwm** [crystalwm/cssDemo#14]
http://www.w3school.com.cn/cssref/pr_text_white-space.asp

规定段落中的文本不进行换行

**Comment by crystalwm** [comment]
这个属性会在单行文本溢出的时候。
http://runjs.cn/code/6slssjyz

```css
{
	  white-space:nowrap; /*为应用text-overflow做准备，禁止换行*/
    overflow:hidden; /*为应用text-overflow做准备，禁止文本溢出显示*/
    text-overflow:ellipsis;  /*兼容IE,Safari(webkit)*/
	  -o-text-overflow:hidden;/*兼容Opera*/
	 -moz-binding:url('ellipsis.xml#ellipsis'); /*兼容Firefox*/
    border-bottom:1px #ff8000 dashed;} 
```

多行文本溢出需要使用js实现了
